### ISSUE TITLE
Remove old tags [COMMENT HERE IF YOU ARE USING A LEGACY ALPHA OR BETA VERSION]

### ISSUE THREAD

**Issue by tstoeckler** [tstoeckler/drupal-core#6]
The repo currently contains tags for old alpha and beta releases, which do not contain a `composer.json` file, because upstream Drupal did not have one in the `core` directory at that time. Because of that these releases are incompatible with the "new" and proper way of using the repository with Composer. Therefore I would like to eventually remove them from the repository.

This can only be seriously considered once there is a new beta release, which will then contain a `composer.json` file.

If you maintain a site which pulls in one of these releases, please leave a note below specifying which tag you require, so that I know to defer the removal.

**Comment by tstoeckler** [comment]
Ok, now that [8.0.0-beta6] (https://github.com/tstoeckler/drupal-core/releases/tag/8.0.0-beta6) has been released, it is time to get rid of the old tags.

I will start by deleting the old alpha-14, alpha-15 and beta-1 tags 1 week from now, as nobody in their right mind should be using those due to [SA-CORE-2014-005] (https://www.drupal.org/SA-CORE-2014-005). If no one complains, beta-2, beta-3 and beta-4 will follow soon after.

**Comment by tstoeckler** [comment]
OK, just did that (a little late). Assuming no one will complain I will remove beta-2, beta-3 and beta-4 one week from now.

**Comment by milkovsky** [comment]
Please add 8.0.0-beta7

**Comment by tstoeckler** [comment]
Just removed the old tags, so closing this. Will add the new beta in a minute.
