### ISSUE TITLE
"web/core" custom installer path skipped

### ISSUE THREAD

**Issue by fago** [tstoeckler/drupal-core#7]
First off, thanks for sharing your subtree split, very useful!

I do not know what's changed, but suddenly my composer.json does not respect the "web/core" custom installer path any more. Does that still work for you? I reproduced it with a very simple composer.json:

```javascript
{
    "name": "drunomics/druweb8",
    "type": "project",
    "require": {
        "composer/installers": "^1.0.20",
        "drupal/core": "8.0.0-beta6",
        "drush/drush": "7.0.0-alpha8"
    },
    "require-dev": {},
    "autoload": {
        "psr-4": {}
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "repositories": [
        {
            "type": "vcs",
            "url": "git@github.com:tstoeckler/drupal-core.git"
        }
    ],
    "scripts": {
        "post-install-cmd": "scripts/composer/post-install.sh"
    },
    "extra": {
        "installer-paths": {
            "web/core": ["type:drupal-core"],
            "web/modules/contrib/{$name}": ["type:drupal-module"],
            "web/profiles/contrib/{$name}": ["type:drupal-profile"],
            "web/themes/contrib/{$name}": ["type:drupal-theme"],
            "web/drush/{$name}": ["type:drupal-drush"]
        }
    },
    "config": {
        "preferred-install": "dist"
    }
}
```

**Comment by tstoeckler** [comment]
Hmm... that's very strange. From the looks of it I don't see anything wrong with the `composer.json`. Can you check what commit of `composer/installers` got installed?

**Comment by tstoeckler** [comment]
And, yes, this still works for me. I've still been using https://github.com/tstoeckler/drupal-site-template in the last days and everything works fine.

**Comment by fago** [comment]
yeah, I've been also using your template (slightly modified). I'm using:
https://api.github.com/repos/composer/installers/zipball/1bff8aa77a18f3616f468ed8000cf86a57
1bff8aa77a18f3616f468ed8000cf86a5725bac3

Strange is I cannot reproduce the issue now on a different machine based on the same repo & composer.lock. I'll try later with the other machine again and restart from scratch if necessary. 

Off-topic, but another issue when using modules from webflo's packagist:
  - Installing drupal/core (8.0.0-beta6)
    Loading from cache
  - Installing drupal/drupal (8.0.0)
    Downloading: 100%         
This leads to drupal/drupal being written into web/core, resulting to a web/core/core directory :/

**Comment by fago** [comment]
ha, looks like there was a temporary bug in composer. After composer self-update it works again on the problematic machine as well!
